packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Auth
  better-auth: ^1.3.4

  # Dev tooling
  eslint: ^9.25.1
  prettier: ^3.5.3
  # tailwindcss: ^3.4.15
  typescript: ^5.9.0-beta

  # Misc
  zod: ^4.0.0

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.83.0
  "@trpc/client": ^11.1.0
  "@trpc/tanstack-react-query": ^11.1.0
  "@trpc/server": ^11.1.0

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.0.12
    "@types/react-dom": ^19.0.4

onlyBuiltDependencies:
  - esbuild
