packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  better-auth: ^1.3.4
  eslint: ^9.33.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.6
  typescript: ^5.9.2
  zod: ^4.0.0
  '@tanstack/react-query': ^5.83.0
  '@trpc/client': ^11.1.0
  '@trpc/tanstack-react-query': ^11.1.0
  '@trpc/server': ^11.1.0
catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.0.12
    '@types/react-dom': ^19.0.4
onlyBuiltDependencies:
  - '@rocicorp/zero-sqlite3'
  - core-js-pure
  - esbuild
